# Category Chnage Constatnts

from enum import Enum

CC_PENDING = 'Pending'
CC_WAITING_FOR_DOCUMENT = "Waiting_for_Document"
CC_PROCESSING = 'Processing'
CC_WAITING_FOR_APPROVAL = "Waiting_for_Approval"
CC_APPROVED = 'Approved'
CC_REJECTED = 'Rejected'

# policy holder admin role name
PH_ADMIN_ROLE = "Policy Holder Admin"

PH_STATUS_CREATED = 'Created'
PH_STATUS_PENDING = 'Pending'
PH_STATUS_APPROVED = 'Approved'
PH_STATUS_REJECTED = 'Rejected'
PH_STATUS_REWORK = 'Rework'
PH_STATUS_LOCKED = 'Locked'
BANK_ACCOUNT_ID = {
    30005: 5,
    30008: 2,
    30011: 13,
    30012: 3,
    30013: 9,
    30014: 10,
    30015: 7,
    30016: 6,
    30018: 11,
    30019: 4,
    30020: 8,
    30021: 12
}

TIPL_PAYMENT_METHOD_ID = 28

class LegalForm(Enum):
    ASSOCIATION_SYNDICAT = 1
    SA_SAU_SAS = 2
    CONFESSION_RELIGIEUSE = 3
    COLLECTIVITE_PUBLIQUE = 4
    COOPERATIVE_SOCIETE_MUTUALISTE_GIE = 5
    ETABLISSEMENT_INDIVIDUEL_EURL = 6
    ETABLISSEMENT_PUBLIC = 7
    FONDATION_ONG = 8
    ORGANISATION_INTERNATIONALE_REPRESENTATION_DIPLO = 9
    SARL_SARLU = 10
    AUTRE = 11

class ActivityCode(Enum):
    AGRICULTURE_ELEVAGE_PECHE = 1
    BANQUES_ASSURANCES_MICROFINANCES = 2
    BATIMENT_TRAVAUX_PUBLICS = 3
    COMMERCES = 4
    ENVIRONNEMENT = 5
    EXPLOITATION_FORESTIERE = 6
    HOTELLERIES_RESTAURATIONS = 7
    INDUSTRIES = 8
    JEUX_LOISIRS = 9
    MINES_SOLIDES = 10
    PETROLE = 11
    PARAPETROLIER = 12
    PROJET = 13
    SANTE_MEDICAMENT = 14
    SERVICES = 15
    TRANSPORT_LOGISTIQUE = 16
    TELECOM_NTIC = 17
    AUTRE = 18

LEGAL_FORM_CHOICES = [e.value for e in LegalForm]

ACTIVITY_CODE_CHOICES = [e.value for e in ActivityCode]