# Generated by Django 3.2.22 on 2023-11-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0018_camu_code_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholderinsuree',
            name='is_payment_done_by_policy_holder',
            field=models.BooleanField(db_column='IsPaymentDoneByPolicyHolder', default=False),
        ),
        migrations.AddField(
            model_name='historicalpolicyholderinsuree',
            name='is_rights_enable_for_insuree',
            field=models.BooleanField(db_column='IsRightsEnableForInsuree', default=False),
        ),
        migrations.AddField(
            model_name='policyholderinsuree',
            name='is_payment_done_by_policy_holder',
            field=models.BooleanField(db_column='IsPaymentDoneByPolicyHolder', default=False),
        ),
        migrations.AddField(
            model_name='policyholderinsuree',
            name='is_rights_enable_for_insuree',
            field=models.BooleanField(db_column='IsRightsEnableForInsuree', default=False),
        ),
    ]
