# Generated by Django 3.2.21 on 2023-12-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0019_auto_20231123_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholderinsuree',
            name='employer_number',
            field=models.CharField(blank=True, db_column='EmployerNumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policyholderinsuree',
            name='employer_number',
            field=models.CharField(blank=True, db_column='EmployerNumber', max_length=50, null=True),
        ),
    ]
