# Generated by Django 3.2.21 on 2024-02-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0022_auto_20240226_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholderexcption',
            name='code',
            field=models.CharField(db_column='ExceptionCode', max_length=255, null=True),
        ),
    ]
