# Generated by Django 3.2.22 on 2024-03-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0023_auto_20240228_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholderexcption',
            name='is_used',
            field=models.BooleanField(db_column='IsUsed', default=False),
        ),
    ]
