# Generated by Django 3.2.22 on 2024-03-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0024_auto_20240304_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholderexcption',
            name='contract_id',
            field=models.UUIDField(db_column='ContractId', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='policyholderexcption',
            name='month',
            field=models.CharField(db_column='Month', max_length=255, null=True),
        ),
    ]
