# Generated by Django 3.2.22 on 2024-04-09 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0052_alter_childtransferrequest_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policyholder', '0025_auto_20240307_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChange',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=256)),
                ('new_category', models.CharField(db_column='NewCategory', max_length=256)),
                ('request_type', models.CharField(db_column='RequestType', max_length=256)),
                ('status', models.CharField(db_column='Status', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CreatedTime')),
                ('modified_time', models.DateTimeField(auto_now=True, db_column='ModifiedTime')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('insuree', models.ForeignKey(db_column='Insuree', on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree')),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('policy_holder', models.ForeignKey(db_column='PolicyHolder', on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.policyholder')),
            ],
            options={
                'db_table': 'tblCategoryChange',
                'managed': True,
            },
        ),
    ]
