# Generated by Django 3.2.21 on 2024-04-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0026_auto_20240409_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorychange',
            name='old_category',
            field=models.CharField(db_column='OldCategory', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='categorychange',
            name='rejected_reason',
            field=models.CharField(db_column='Reason', max_length=256, null=True),
        ),
    ]
