# Generated by Django 3.2.21 on 2024-04-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0027_auto_20240410_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorychange',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
    ]
