# Generated by Django 3.2.22 on 2024-04-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0029_auto_20240419_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='is_review',
            field=models.BooleanField(db_column='IsReview', default=False),
        ),
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='is_submit',
            field=models.BooleanField(db_column='IsSubmit', default=False),
        ),
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='request_number',
            field=models.CharField(db_column='RequestNumber', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='is_review',
            field=models.BooleanField(db_column='IsReview', default=False),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='is_submit',
            field=models.BooleanField(db_column='IsSubmit', default=False),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='request_number',
            field=models.CharField(db_column='RequestNumber', max_length=255, null=True),
        ),
    ]
