# Generated by Django 3.2.22 on 2024-04-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0032_auto_20240425_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='form_ph_portal',
            field=models.BooleanField(db_column='FormPhPortal', default=False),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='form_ph_portal',
            field=models.BooleanField(db_column='FormPhPortal', default=False),
        ),
    ]
