# Generated by Django 3.2.21 on 2024-05-22 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policyholder', '0033_auto_20240429_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholderinsuree',
            name='user',
            field=models.ForeignKey(blank=True, db_column='PortalUser', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyholderinsuree',
            name='user',
            field=models.ForeignKey(blank=True, db_column='PortalUser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
