# Generated by Django 3.2.22 on 2024-07-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0034_auto_20240522_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='erp_partner_id',
            field=models.CharField(blank=True, db_column='ErpPartnerID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='erp_partner_id',
            field=models.CharField(blank=True, db_column='ErpPartnerID', max_length=255, null=True),
        ),
    ]
