# Generated by Django 3.2.25 on 2024-09-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0036_auto_20240702_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='is_blocked',
            field=models.BooleanField(db_column='IsBlocked', default=False),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='is_blocked',
            field=models.BooleanField(db_column='IsBlocked', default=False),
        ),
    ]
