# Generated by Django 3.2.25 on 2024-07-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0036_auto_20240702_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyholdermutation',
            old_name='policy_holder',
            new_name='policyholder',
        ),
        migrations.AlterField(
            model_name='policyholdermutation',
            name='policyholder',
            field=models.ForeignKey(db_column='policy_holder_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='policyholder.policyholder'),
        ),
    ]
