# Generated by Django 3.2.25 on 2025-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0038_auto_20250227_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionReason',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reason', models.CharField(db_column='reason', max_length=255, null=True)),
                ('period', models.IntegerField(db_column='period')),
                ('scope', models.CharField(db_column='scopeReason', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedTime')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='ModifiedTime')),
            ],
            options={
                'db_table': 'tblExceptionReason',
                'managed': True,
            },
        ),
    ]
