# Generated by Django 3.2.25 on 2025-07-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0039_exceptionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholderexcption',
            name='reason',
            field=models.ForeignKey(db_column='reason', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.exceptionreason'),
        ),
    ]
