# Generated by Django 3.2.25 on 2025-08-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0040_policyholderexcption_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholderexcption',
            name='ended_at',
            field=models.DateTimeField(db_column='EndedAt', null=True),
        ),
        migrations.AddField(
            model_name='policyholderexcption',
            name='started_at',
            field=models.DateTimeField(db_column='StartedAt', null=True),
        ),
    ]
