# Generated by Django 3.2.25 on 2025-09-21 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policyholder', '0041_auto_20250820_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHolderUserPending',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('policy_holder', models.ForeignKey(db_column='PolicyHolderId', on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.policyholder')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblPolicyHolderUserPending',
                'managed': True,
            },
        ),
    ]
