# Generated by Django 3.2.25 on 2026-01-14 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policyholder', '0042_policyholderuserpending'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHolderInsureeUploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name_hash', models.CharField(db_column='FileNameHash', max_length=255)),
                ('file_path', models.CharField(blank=True, db_column='FilePath', max_length=255, null=True)),
                ('policy_holder', models.ForeignKey(db_column='PolicyHolderUUID', on_delete=django.db.models.deletion.CASCADE, related_name='insuree_uploaded_files', to='policyholder.policyholder')),
            ],
            options={
                'db_table': 'policyholder_PolicyHolderInsureeUploadedFile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolicyHolderInsureeBatchUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file_name', models.CharField(db_column='InputFileName', help_text='Original uploaded file name', max_length=255)),
                ('results', models.JSONField(blank=True, db_column='Results', help_text='Row-specific results stored as JSON array with ligne, nom, prenom, numero_camu, Etat, remarque', null=True)),
                ('celery_task_id', models.CharField(blank=True, db_column='CeleryTaskID', help_text='Celery AsyncResult task ID', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_column='Status', default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(db_column='TotalRows', default=0, help_text='Total rows to process (excluding header)')),
                ('processed_rows', models.IntegerField(db_column='ProcessedRows', default=0, help_text='Number of rows processed so far')),
                ('success_count', models.IntegerField(db_column='SuccessCount', default=0, help_text='Number of successfully processed rows')),
                ('error_count', models.IntegerField(db_column='ErrorCount', default=0, help_text='Number of rows with errors')),
                ('started_at', models.DateTimeField(blank=True, db_column='StartedAt', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='CompletedAt', null=True)),
                ('error_message', models.TextField(blank=True, db_column='ErrorMessage', help_text='Error message if status is FAILED', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy_holder', models.ForeignKey(db_column='PolicyHolderUUID', on_delete=django.db.models.deletion.CASCADE, related_name='insuree_batch_uploads', to='policyholder.policyholder')),
            ],
            options={
                'db_table': 'policyholder_PolicyHolderInsureeBatchUpload',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='policyholderinsureebatchupload',
            index=models.Index(fields=['celery_task_id'], name='policyholde_CeleryT_1e8cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='policyholderinsureebatchupload',
            index=models.Index(fields=['policy_holder', 'created_at'], name='policyholde_PolicyH_28cf39_idx'),
        ),
        migrations.AddIndex(
            model_name='policyholderinsureebatchupload',
            index=models.Index(fields=['status', 'created_at'], name='policyholde_Status_f861b0_idx'),
        ),
    ]
